## Program stderr:                                                                                                                              │
│            ▗▖ ▗▖▗▄▄▄▖▗▄▄▖ ▗▖  ▗▖▗▄▄▄▖▗▖   ▗▄▄▖  ▗▄▖ ▗▄▄▄▖                                                            ││```                                                                                                                                             │
│            ▐▌▗▞▘▐▌   ▐▌ ▐▌▐▛▚▖▐▌▐▌   ▐▌   ▐▌ ▐▌▐▌ ▐▌  █                                                              ││multiprocessing.pool.RemoteTraceback:                                                                                                           │
│            ▐▛▚▖ ▐▛▀▀▘▐▛▀▚▖▐▌ ▝▜▌▐▛▀▀▘▐▌   ▐▛▀▚▖▐▌ ▐▌  █                                                              ││\"\"\"                                                                                                                                          │
│            ▐▌ ▐▌▐▙▄▄▖▐▌ ▐▌▐▌  ▐▌▐▙▄▄▖▐▙▄▄▖▐▙▄▞▘▝▚▄▞▘  █                                                              ││Traceback (most recent call last):                                                                                                              │
│                                                                                                                      ││  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py\", line 2597, in _run_ninja_build                                 │
│                      POPCORN CLI - GPU MODE                                                                          ││    subprocess.run(                                                                                                                             │
│                                                                                                                      ││  File \"/usr/lib/python3.10/subprocess.py\", line 526, in run                                                                                  │
│          ┌────────────────────────────────────────────┐                                                              │█    raise CalledProcessError(retcode, process.args,                                                                                             │
│          │  ╔══════════════════════════════════╗  ϟϟϟ │                                                              │█subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 255.                                                     │
│          │  ║ ▄▄ Graphics Processing Unit  ▄▄║ ║      │▒                                                             │█                                                                                                                                                │
│          │  ║ ██████  80GB HBM3 MEMORY  █████║ ║      │▒                                                             │█The above exception was the direct cause of the following exception:                                                                            │
│          │  ║ ▀▀▀▀▀▀  700W TDP          █████║ ║      │▒                                                             │█                                                                                                                                                │
│          │  ╚══════════════════════════════════╝      │▒                                                             │█Traceback (most recent call last):                                                                                                              │
│          │   ┌─────┐┌─────┐┌─────┐┌─────┐┌─────┐     │▒                                                              │█  File \"/usr/lib/python3.10/multiprocessing/pool.py\", line 125, in worker                                                                     │
│          │   │:::::││:::::││:::::││:::::││:::::│     │▒                                                              │█    result = (True, func(*args, **kwds))                                                                                                        │
│          │   └─────┘└─────┘└─────┘└─────┘└─────┘     │▒                                                              │█  File \"/home/runner/_work/discord-cluster-manager/discord-cluster-manager/eval.py\", line 154, in _run_single_test                            │
│          │  ┌──────────────────────────────────┐      │▒                                                             │█    submission_output = custom_kernel(_clone_data(data))                                                                                        │
│          │  │    discord.com/invite/gpumode    │      │▒                                                             │█  File \"/home/runner/_work/discord-cluster-manager/discord-cluster-manager/submission.py\", line 378, in custom_kernel                         │
│          │  │    ═══╧═══╧═══╧═══╧═══╧═══╧═══   │      │▒                                                             │█    mod = get_module()                                                                                                                          │
│          │  └──────────────────────────────────┘      │▒                                                             │█  File \"/home/runner/_work/discord-cluster-manager/discord-cluster-manager/submission.py\", line 325, in get_module                            │
│          └────────────────────────────────────────────┘▒                                                             │█    module = load_inline(                                                                                                                       │
│           ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                                                                 │█  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py\", line 2051, in load_inline                                      │
│             ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀                                                                   │█    return _jit_compile(                                                                                                                        │
│                                                                                                                      │█  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py\", line 2134, in _jit_compile                                     │
│                                                                                                                      │█    _write_ninja_file_and_build_library(                                                                                                        │
│                                                                                                                      │█  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py\", line 2286, in _write_ninja_file_and_build_library              │
│                                                                                                                      │█    _run_ninja_build(                                                                                                                           │
│                                                                                                                      │█  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py\", line 2614, in _run_ninja_build                                 │
│                                                                                                                      │█    raise RuntimeError(message) from e                                                                                                          │
│                                                                                                                      │█RuntimeError: Error building extension 'ultimate_fp4_gemv_mma'                                                                                  │
│                                                                                                                      │█\"\"\"                                                                                                                                          │
│                                                                                                                      │█                                                                                                                                                │
│                                                                                                                      │█The above exception was the direct cause of the following exception:                                                                            │
│                                                                                                                      │█                                                                                                                                                │
│                                                                                                                      │█Traceback (most recent call last):                                                                                                              │
│                                                                                                                      │█  File \"/home/runner/_work/discord-cluster-manager/discord-cluster-manager/eval.py\", line 485, in <module>                                    │
│                                                                                                                      │█    sys.exit(main())                                                                                                                            │
│                                                                                                                      │█  File \"/home/runner/_work/discord-cluster-manager/discord-cluster-manager/eval.py\", line 451, in main                                        │
│                                                                                                                      │█    return run_testing(logger, pool, tests)                                                                                                     │
│                                                                                                                      │█  File \"/home/runner/_work/discord-cluster-manager/discord-cluster-manager/eval.py\", line 184, in run_testing                                 │
│                                                                                                                      │█    good, message = run_single_test(pool, test)                                                                                                 │
│                                                                                                                      │█  File \"/home/runner/_work/discord-cluster-manager/discord-cluster-manager/eval.py\", line 167, in run_single_test                             │
│                                                                                                                      ││    return pool.apply(_run_single_test, (test,))                                                                                                │
│                                                                                                                      ││  File \"/usr/lib/python3.10/multiprocessing/pool.py\", line 360, in apply                                                                      │
│                                                                                                                      ││    return self.apply_async(func, args, kwds).get()                                                                                             │
│                                                                                                                      ││  File \"/usr/lib/python3.10/multiprocessing/pool.py\", line 774, in get                                                                        │
│                                                                                                                      ││    raise self._value                                                                                                                           │
│                                                                                                                      ││RuntimeError: Error building extension 'ultimate_fp4_gemv_mma'```                                                                               │
│                                                                                                                      ││                                                                                                                                                │
│                                                                                                                      ││## Program stdout:                                                                                                                              │
│                                                                                                                      ││```                                                                                                                                             │
│                                                                                                                      ││[1/3] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=ultimate_fp4_gemv_mma -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/local/lib/python3.10/dist│
│                                                                                                                      ││[2/3] /usr/local/cuda-13.0/bin/nvcc --generate-dependencies-with-compile --dependency-output cuda.cuda.o.d -DTORCH_EXTENSION_NAME=ultimate_fp4_g│
│                                                                                                                      ││FAILED: [code=255] cuda.cuda.o                                                                                                                  │
│                                                                                                                      ││/usr/local/cuda-13.0/bin/nvcc --generate-dependencies-with-compile --dependency-output cuda.cuda.o.d -DTORCH_EXTENSION_NAME=ultimate_fp4_gemv_mm│
│                                                                                                                      ││/home/runner/.cache/torch_extensions/py310_cu129/ultimate_fp4_gemv_mma/cuda.cu(129): warning #177-D: variable \"k_bytes_start\" was declared but│
│                                                                                                                      ││          const int k_bytes_start = k_start / 2;                                                                                                │
│                                                                                                                      ││                    ^                                                                                                                           │
│                                                                                                                      ││                                                                                                                                                │
│                                                                                                                      ││Remark: The warnings can be suppressed with \"-diag-suppress <warning-number>\"                                                                 │
│                                                                                                                      ││                                                                                                                                                │
│                                                                                                                      ││/home/runner/.cache/torch_extensions/py310_cu129/ultimate_fp4_gemv_mma/cuda.cu(111): warning #177-D: variable \"smem_reduce\" was declared but n│
│                                                                                                                      ││                               float smem_reduce[kWarps][kWarpM];                                                                               │
│                                                                                                                      ││                                     ^                                                                                                          │
│                                                                                                                      ││                                                                                                                                                │
│                                                                                                                      ││/home/runner/.cache/torch_extensions/py310_cu129/ultimate_fp4_gemv_mma/cuda.cu(27): warning #177-D: variable \"kWarpK\" was declared but never r│
│                                                                                                                      ││  constexpr int kWarpK = 64;                                                                                                                    │
│                                                                                                                      ││                ^                                                                                                                               │
│                                                                                                                      ││                                                                                                                                                │
│                                                                                                                      ││ptxas error   : Entry function '_Z25fused_fp4_gemv_mma_kernelPKhS0_S0_S0_PN7cutlass6half_tEiii' uses too much shared data (0x468c4 bytes, 0xc000│
│                                                                                                                      ││ninja: build stopped: subcommand failed.```","**NVIDIA on GitHub (secret) ✅ success**                                                          │
│                                                                                                                      ││> Workflow [19256573452](<https://github.com/gpu-mode/discord-cluster-manager/actions/runs/19256573452>) completed                              │
│                                                                                                                      ││> Downloading artifacts... done                                                                                                                 │
│                                                                                                                      ││> ❌ Running tests failed (internal error 1)                                                                                                    │
│                                                                                                                      ││"
